### ISSUE TITLE
Improve build times 

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb-python#88]
Build times have gotten longer with  panda: From an average of 6 mins to 1 hour.

(They don't really take 1 hour because travis runs many jobs at a time) 

Would there be a clever way to speed them up? I would not want to reduce testing just for the sake of faster builds tho.

**Comment by robbyt** [comment]
@ReAzem you should try using a pip wheels to speed up the build: 
https://packaging.python.org/en/latest/installing.html#installing-cached-wheels

**Comment by georgijd** [comment]
I think we can try using the caching option in travis by modifiying .travis.yml.
```yaml
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
```

Any thoughts? Waiting for more than an hour to see if one's build is successful is really frustrating.
